### ISSUE TITLE
typos in x86asm instruction table

### ISSUE THREAD

**Issue by xem** [mazegen/x86reference#2]
Hello, I'm writig a disassembler for fun (and your work is very useful!)

It looks like you made a typo:

http://ref.x86asm.net/coder32.html

"FXCH ST1" seems to be encoded "D9 C9", not "D9 C9 /1"

"FADDP STi ST0" is not "DE" but "DE C0+i"

etc...

Are you interested in other reports of this kind?

**Comment by mazegen** [comment]
Hello xem,
thank you for your reports.

As for the FXCH, this is because of the strange Intel syntax. Opcode D9C9 should be disassembled as FXCH with no operands. Note that the 0xC9 actually is a ModR/M byte that defines operands "ST, ST1". Therefore, the opcode extension "1" is also indicated in the reference.

There are many similar exceptions to the usual "general" syntax in the x87 instruction set, see for example D8D9 FCOMP. You might want to ignore these ones in your disaasembler and always disassemble them with explicit "ST, ST1" operands.

The DEC0+i FADDP works like the following: The 0xDE opcode is always followed by the ModR/M, although the Intel manuals document it as 0xC0+i byte in case of FADDP. However, in this case the instruction depends on the Mod field in the ModR/M byte: if it is 11bin, the instruction is FADDP, otherwise it is FIADD. Welcome to the world of strange x87 encodings. I can recommend this implementation (pseudocode):

    if (opcode == 0xDE) {
      // there is always ModR/M byte, Intel manuals sucks here
      if (ModRM.Mod == 11bin) {
        mnemonic = "FADDP";
        decode_x87_modrm_usual_way();
      }
      else {
        mnemonic = "FIADD";
        decode_x87_ST_operand();
        load_m16_int_value();
      }
    }

Feel free to report other weird instructions and encodings, I'll try to explain them.

**Comment by xem** [comment]
Thanks a lot for all these details. Indeed, the world of x86 (and x87) binary is very strange for a beginner like me, and sadly Intel isn't exhaustive in its own documentation, which is awkward. Sometimes it's hard to find explanations like the ones you gave above, especially when we have to deal with ambiguities (many instructions with the same opcode). 
Your work is amazing though, and helps fix that. thanks!

**Comment by xem** [comment]
Sorry to bother you but I have a problem with one instruction disassembling, as you can see in [this demo](https://xem.github.io/minix86/src/disassembler.html) at the address @0121.
The disassembler encounters the bytes "DE 4C 3D", recognizes the pattern "DE/1" (fimul m16int), uses the ModR/M byte "4C" to interpret the operand as "[si + disp8]", and uses the last byte "3D" to read the value of "disp8" (61). But in the original asm code, you can read the following lines:

````
@0121: fimul word  [byte si+val]
(...)
@013D: val: dw 6519
````
I have no idea how this value can be retrieved from the binary code instead of "61".
Thanks a lot if you can help with this :)

**Comment by mazegen** [comment]
I think your disassembly is correct but your disassembler doesn't know the `SI` value and can't interpret the 0x3D as offset of the word at @013D. I don't remember the rules of a .COM program. If `SI` is always initialized with the entry point offset, you can calculate it as 0x100 + 0x3D = 0x13D and interpret is as 16-bit data.

**Comment by xem** [comment]
Ha, of course. I didn't see that "3D" was just the address of the data I was looking for minus 0x100.
SI is indeed initialized to 0x100. (I even wrote it in [my documentation](https://github.com/xem/minix86/blob/gh-pages/TLDR.md)
Sorry, and thanks! :D
